{% set name = "pikepdf" %}
{% set version = "10.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1396843aae147328bf221b778725636a1cf33080a46a583b1d18fbb0ca2bcd3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - wheel >=0.37
    - pybind11 >=3
    - qpdf >=11.9.0
  run:
    - python
    - pillow >=10.0.1
    - deprecated
    - lxml >=4.8
    - packaging

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pikepdf

about:
  home: https://github.com/pikepdf/pikepdf
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: A Python library for reading and writing PDF, powered by qpdf
  doc_url: https://pikepdf.readthedocs.io/
  dev_url: https://github.com/pikepdf/pikepdf

extra:
  recipe-maintainers:
    - carlodri
