{% set name = "pikepdf" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40f37da54bc02f3714c17454e1aee28d02fdc28ea0b7903240eae9d53c360b2b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=61
    - wheel >=0.37
    - pybind11 >=2.10.1,<3
    - qpdf >=11.9.1
  run:
    - python
    - setuptools
    - pillow >=10.0.1
    - deprecated
    - qpdf >=11.9.1
    - lxml >=4.8
    - packaging

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pikepdf    # [build_platform != target_platform]

about:
  home: https://github.com/pikepdf/pikepdf
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: A Python library for reading and writing PDF, powered by qpdf
  doc_url: https://pikepdf.readthedocs.io/
  dev_url: https://github.com/pikepdf/pikepdf

extra:
  recipe-maintainers:
    - carlodri
