{% set name = "pikepdf" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1eccc798868806e784bcce73a48bbb434b8b7336540d5567f9ab8536ca6b66a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
    - pybind11 >=2.4.3,< 3
    - qpdf >=8.4.2
  run:
    - python
    - setuptools
    - lxml >=4
    - qpdf >=8.4.2

test:
  imports:
    - pikepdf

about:
  home: https://github.com/pikepdf/pikepdf
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: A Python library for reading and writing PDF, powered by qpdf
  doc_url: https://pikepdf.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/pikepdf/pikepdf

extra:
  recipe-maintainers:
    - carlodri
